services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BACKEND_URL: ${VITE_BACKEND_URL}
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules:cached
    ports:
      - "3001:3001"
    environment:
      - BUN_INSTALL_FROZEN=1

volumes:
  node_modules: {}
